short-key:
  gcp: "git-commit-push"
  gcb: "git-new-branch"
cmds:
  git-commit-push:
    - "git add ."
    - "git commit -m${remark}"
    - "git pull"
    - "git push"
  git-new-branch:
    - "git checkout master"
    - "git pull"
    - "git checkout -b ${branchName}"
    - "git push --set-upstream origin ${branchName}"
examples:
  git-commit-push: "tools gcp first-commit"
  git-new-branch: "tools gcb feature/robin_wechat_20221109"